[project]
name = "cli-agent"
version = "0.1.0"
description = "A tool-calling LLM agent with the personality of Ame-chan from NSO."
readme = "README.md"
requires-python  = ">=3.11"
license = { text = "MIT"}
authors = [{ name = "toffeezzz"}]
dependencies = [
  "openai",
  "rich",
  "pydantic",
  "pydantic-settings",
  "send2trash",
  "python-dotenv",
  "prompt-toolkit"
]

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
cli-agent = "ame.__main__:main"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

